name: Continuous Integration Checks

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Build image
      run: |
        docker build . --file Dockerfile --tag vendingmachine:latest
